trigger:
  branches:
    include:
      - master

stages:
  - stage: Build
    jobs:
      - job: BuildReactApp
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '20.x'
            displayName: 'Install Node.js'
          - script: |
              npm install
              npm run build
            displayName: 'Build React App'
          - task: ArchiveFiles@2
            displayName: "archive"
            inputs:
              rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist'
              includeRootFolder: true
              archiveType: zip
              archiveFile: $(System.DefaultWorkingDirectory)/archive.zip
              replaceExistingArchive: true
              verbose: true

          - task: AzureWebApp@1
            inputs:
              azureSubscription: '9d33f830-0de4-466e-9373-1d9945951cb6'
              resourceGroupName: test-rg
              appName: 'devops-test-appmy'
              package: $(System.DefaultWorkingDirectory)/archive.zip
              startUpCommand: 'npm start'
              appType: 'webApp'
              deploymentMethod: 'auto'
            displayName: 'Deploy to Azure Web App'